---
- name: Update httpd and start service
  hosts: all
  become: true

  tasks:
    - name: Check OS version
      register: os_version
      setup:
        filter: ansible_distribution_major_version

    - name: Install httpd package
      yum:
        name: httpd
        state: latest
      when: os_version['ansible_facts']['ansible_distribution_major_version'] == '7'

    - name: Install httpd package
      dnf:
        name: httpd
        state: latest
      when: os_version['ansible_facts']['ansible_distribution_major_version'] == '8'

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true
