---
- name: Install git and Python
  hosts: all
  become: true

  tasks:
    - name: Install git
      package:
        name: git
        state: latest

    - name: Install Python
      package:
        name: python
        state: latest

