---
- name: Execute ls command on all hosts
  hosts: all
  become: true

  tasks:
  - name: Run ls command
    command: ls
    register: ls_output

  - name: Print ls output
    debug:
      var: ls_output.stdout_lines


