---
- name: Create ansible-user
  hosts: all
  become: true
  vars:
    username: ansible-user
    password: abc123
  tasks:
  - name: Create user
    user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash
      createhome: yes


