---
- name: Install Nginx on all hosts
  hosts: all
  become: true
  tasks:
    - name: Check OS version
      ansible.builtin.setup:
        filter: ansible_distribution_release
      register: os_version

    - name: Install Nginx on Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: os_version['ansible_distribution_release'] == 'xenial'

    - name: Install Nginx on CentOS
      ansible.builtin.yum:
        name: nginx
        state: latest
      when: os_version['ansible_distribution_release'] == 'centos'

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
