---
- name: Install and configure httpd
  hosts: all
  become: true

  tasks:
  - name: Check OS version
    debug:
      msg: "The OS version of {{ inventory_hostname }} is {{ ansible_distribution }} {{ ansible_distribution_version }}"

  - name: Install httpd
    yum:
      name: httpd
      state: latest

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Echo "I LOVE ANSIBLE AUTOMATION" to index.html
    shell: echo "I LOVE ANSIBLE AUTOMATION" > /var/www/html/index.html

