---
- hosts: all
  become: true
  
  tasks:
    - name: Install Tomcat 8
      apt:
        name: tomcat8
        state: present

    - name: Start Tomcat 8
      service:
        name: tomcat8
        state: started