---
- name: Check uptime on all hosts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check uptime
      command: uptime
      register: uptime_output
    - name: Print uptime
      debug:
        var: uptime_output.stdout_lines
